version: '3'

services:
  app-noode:
    build: .
    image: node-app
    container_name: app-node
#    environment:
#      - PORT=4000
#      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - database-layer
    volumes:
      - .:/usr/src/node-app
    networks:
      - shared-network
    restart: on-failure

  database-layer:
    image: postgres:12-alpine
    container_name: database-layer
    environment:
#        - DB_POSTGRES=true
#        - PGPORT=${DB_PORT}
#        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=password
#        - POSTGRES_DB=${DB_NAME}
#    ports:
#      - "${DB_PORT}:${DB_PORT}"
    networks:
      - shared-network
    volumes:
      - database-volume:/var/lib/postgresql/data
    restart: on-failure

volumes:
  database-volume:

networks:
  shared-network:
